# Generated by Django 3.2.3 on 2021-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
