# Generated by Django 3.2.3 on 2021-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210604_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
