# Generated by Django 3.2.3 on 2021-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20210604_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
